### ISSUE TITLE
Next.js version?

### ISSUE THREAD

**Issue by karlhorky** [Knochenmark/gatsby-starter-level-2#131]
Hi there, first of all, thanks for this starter, very cool!

**Is your feature request related to a problem? Please describe.**

It would be nice to be able to use this template with Next.js

**Describe the solution you'd like**

A version of the template in Next.js

**Describe alternatives you've considered**

Having the community create this Next.js version

**Comment by Knochenmark** [comment]
I'm closing this, since it's not really an issue with this gatsby starter but more of a request for a new project.

Technically there shouldn't be an issue to migrate React components from Gatsby towards Next.js. Even migrating the styling should be mostly copy paste, even though I know that Next.js by defautl rather uses Css-Modules and I'm using emotion.
